spring.application.name=employee-management
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management
spring.datasource.username=postgres
spring.datasource.password=Hieu14997@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=dev

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

spring.cache.type=caffeine
spring.cache.cache-names=employeeCount
spring.cache.caffeine.spec=expireAfterWrite=1m

jwt.secret=01234567890123456789012345678901
jwt.expiration=3600